name: Skyblock
main: xyz.oribuin.skyblock.SkyblockPlugin
version: '1.0'
api-version: '1.20'
authors: [ 'Oribuin' ]
description: custom skyblock plugin :-)
loadbefore:
  - Multiverse-Core
softdepend:
  - PlaceholderAPI
  - WorldEdit
  - FastAsyncWorldEdit
  - AsyncWorldEdit
  - Vault
permissions:
  skyblock.use:
    description: Allows the player to use the skyblock command.
    default: op
  skyblock.biome:
    description: Allows the player to change the biome of their island.
    default: op
  skyblock.border:
    description: Allows the player to change the border of their island.
    default: op
  skyblock.create:
    description: Allows the player to create an island.
    default: op
  skyblock.invite:
    description: Allows the player to invite other players to their island.
    default: op
    children:
      skyblock.invite.accept:
        description: Allows the player to accept an island invite.
      skyblock.invite.deny:
        description: Allows the player to deny an island invite.
        default: op
      skyblock.send:
        description: Allows the player to teleport to other players islands.
        default: op
    skyblock.leave:
      description: Allows the player to leave their island.
      default: op
  skyblock.lock:
    description: Allows the player to lock their island.
    default: op
  skyblock.members:
    description: Allows the player to view the members of their island.
    default: op
  skyblock.teleport:
    description: Allows the player to teleport to their island.
    default: op
  skyblock.warp:
    description: Allows the player to warp to their island.
    default: op
    children:
      skyblock.warp.category:
        description: Allows the player to change the category of their island.
        default: op
      skyblock.warp.icon:
        description: Allows the player to change the icon of their island.
        default: op
      skyblock.warp.name:
        description: Allows the player to change the name of their island.
        default: op
      skyblock.warp.settings:
        description: Allows the player to change the settings of their island.
        default: op
      skyblock.warp.teleport:
        description: Allows the player to teleport to other islands.
        default: op
      skyblock.warp.upvote:
        description: Allows the player to upvote other islands.
        default: op